### PR TITLE
Post form based

### LINKED ISSUE #58: Post: form based views
Same as #50 and #57 but for the post app

### LINKED ISSUE #126: Can't use special characters in LDB search
When searching for persons or organizations in ldb, using a special character generates a 500 Internal Server Error.

Details:
```
Internal Server Error: /dienst2/ldb/people/search/
Traceback (most recent call last):
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/newrelic-2.56.0.42/newrelic/hooks/framework_django.py", line 499, in wrapper
    return wrapped(*args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/newrelic-2.56.0.42/newrelic/hooks/framework_django.py", line 872, in wrapper
    return wrapped(*args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/www/dienst2/ldb/views.py", line 78, in get
    return super(ResultsView, self).get(request, *args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/views/generic/base.py", line 158, in get
    context = self.get_context_data(**kwargs)
  File "/srv/www/dienst2/ldb/views.py", line 68, in get_context_data
    results = self.get_results()
  File "/srv/www/dienst2/ldb/views.py", line 56, in get_results
    search_term = convert_free_search(q)
  File "/srv/www/dienst2/dienst2/extras.py", line 36, in convert_free_search
    return ' '.join([search_format.format(word) for word in string.split(' ')])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb1' in position 6: ordinal not in range(128)
```

### PR DESCRIPTION
**Pull request by jgadelange**
Fix #58 
Also fixes #126 

Overzicht:
image

Weekoverzicht:
image

AV overzicht:
image

AV overzicht print:
image

### CODE REVIEW

**Comment by praseodym** [comment]
Looking good! Some small issues remain:
- [ ] Layout problems with production data (larger width fields):
screen shot 2016-03-19 at 19 13 29
- [ ] Styling of sender/receiver (should be called recipient..)/category is weird. I noticed it flashes with correct styling when loading.
- [ ] Maybe we want to invert previous/next buttons on the overview page, to make it function in line with the week overview?
- [ ] URL is `post//`, `post/` doesn't work.

**Comment by jgadelange** [comment]
image

**Comment by praseodym** [comment]
Nice! I put the button on the same line, what do you think about that?

**Comment by jgadelange** [comment]
Didn't do that because of the grid system (these are all 3 columns ;))

**Comment by jgadelange** [comment]
I suppose this is not the way it should be used, but it works:
image

**Comment by jgadelange** [comment]
@svenvanhal, what do you think? After all, you are the one that has to work with it..

**Comment by praseodym** [comment]
LGTM, :shipit:

**Comment by jgadelange** [comment]
@svenvanhal?

**Pull request merged**
