### PR TITLE
Prevent merit members from not having a date_from

### LINKED ISSUE #186: Merit member state can be 'not a member'
If a merit member does not have member_date_from set (but only merit_date_from), the person is not considered to be a member.

### PR DESCRIPTION
**Pull request by Fastjur**
This PR prevents merit members from having a merit_from_date set if they haven't got a regular from_date, preventing the issue where some merit_members displayed as 'not a member'. Also has a migration that fills in the date_from where only merit_date_from is set.

**Please note:** Django is unable to recognize the query `person___member_status` due to the 3rd underscore in the `_member_status` field. We are not able to update a persons _membership_status if the query applies to them and it fills in their `date_from` field. After merging we MUST run the management command `clean_persons` with `--save`

Fixes #186 

Also currently blocked by #178 (due to migrations)

Signed-off-by: Jurriaan Den Toonder <jur.den.toonder@gmail.com>

### CODE REVIEW

**Comment by Fastjur** [comment]
Failing build was due to migrations. Fixed now!

**Comment by Fastjur** [comment]
Updated this to also add the check to honorary members and rebased on master

**Comment by jgadelange** [comment]
May be squashed before merging, but otherwise: still LGTM 👍

**Comment by praseodym** [comment]
> After merging we MUST run the management command `clean_persons` with `--save`

Tried doing that, but failed: #255

**Pull request merged**
