### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by praseodym**

### CODE REVIEW

**Comment by jgadelange** [comment]
Are we going to drop all python 2 support? Because now we have some things that will work in both python 2 and 3 and some things that won't, that's a bit messy I think.

**Comment by praseodym** [comment]
Haven't actually tested with Python 2, so it could be that some stuff only works on Python 3. I'm fine with dropping support for Python 2.

**Comment by jgadelange** [comment]
In that case I think we should update the README as well. (and maybe remove some of the stuff that is extra especially for python 2 compatibility) 

I will try to run it later this week to check if everything works.

**Comment by jgadelange** [comment]
Can't seem to break it anymore!

**Comment by hermanbanken** [comment]
Looks like its broken through, according to the flood of e-mails in our mailboxes... At least 1 error was related to not having a `has_key` property which seems so be Python 2 only, inside de mimeparse package. Is someone downgrading?

**Comment by jgadelange** [comment]
That's an error caused by mimeparse... Apparently there is `mimeparse` and `python-mimeparse`, just removed `mimeparse` and installed `python-mimeparse`

**Comment by jgadelange** [comment]
Seems to do the trick 😄

**Pull request merged**
