### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by praseodym**
https://dienst2.chnet/

### CODE REVIEW

**Comment by praseodym** [comment]
```
Internal Server Error: /kas/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/compressor/base.py", line 260, in precompile
    mod = import_module(mod_name)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'lessc {infile} {outfile}'
```

**Comment by jgadelange** [comment]
Shouldn't Travis also do some docker checking?

**Comment by praseodym** [comment]
Maybe it should, but just building the container isn't all too useful.

**Comment by praseodym** [comment]
@jgadelange mergen?

**Pull request merged**
