### PR TITLE
Update kixcode to adhere to PostNL standards.

### LINKED ISSUE #123: KIX code is generated incorrectly
For addresses like "Mekelweg 4b, 2628CD Delft", the KIX-code "2628CD4d" is generated when exporting the address. According to the KIX-guidelines from PostNL, additions to the house number (like the "d" in the example) require an "X" after the regular house number.

Currently: ```2628CD4b```
Correct: ```2628CD4Xb```

Source: http://www.postnl.nl/Images/Brochure-KIX-code-van-PostNL_tcm10-10210.pdf

### PR DESCRIPTION
**Pull request by svenvanhal**
Fixes #123.

### CODE REVIEW

**Comment by jgadelange** [comment]
I would say the kixcode should be a property on the model and should not be created in the export. If the current export functionality does not support that, maybe it should be a separate function?

**Comment by praseodym** [comment]
The new function is not used in export yet?

**Comment by jgadelange** [comment]
I just tried to use the property in the current export... I have no clue how it would work :')

**Comment by svenvanhal** [comment]
@praseodym @jgadelange Me neither, but since the new export functionality is long overdue, I wouldn't put too much time in patching the old one.

**Comment by jgadelange** [comment]
Then I think it would be best for now to also add it in the old export the way you did before.

**Comment by Fastjur** [comment]
This is a PR from 2015. Is this still relevant?

**Comment by jgadelange** [comment]
Don't know. Do we still print [kix-codes](https://www.postnl.nl/klantenservice/bestellen-en-downloaden/documentatie-downloaden/kix-code/) on our outgoing mail?

**Comment by Fastjur** [comment]
That we still do! But it seems to work fine 🙃

**Comment by JoepdeJong** [comment]
I am closing this issue since no problems have occurred with kixcodes for the past few years.

**Pull request closed without merging**
